all:
	g++ sorting.cpp swap.cpp bubble-sort.cpp insertion-sort.cpp selection-sort.cpp merge-sort.cpp -o sorting.exe
	g++ random-list.cpp -o random-list.exe
clean:
	rm -f sorting.exe random-list.exe